In [82]:
#we are uploading the source file into google colab to be able to access it
data_file = 'makeSenseOfCensus.csv'
import numpy as np
data = np.genfromtxt(data_file, delimiter=",", skip_header=1,dtype=int)
print("data:\n",data)



data:
 [[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [48 13  4 ...  0 58  1]
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]]


In [83]:
#adding a new row to the initial data using (np.concatenate())
new_record = [[50,9,4,1,0,0,40,0]]
np.concatenate([data,new_record])


array([[39, 13,  4, ...,  0, 40,  0],
       [50, 13,  4, ...,  0, 13,  0],
       [38,  9,  4, ...,  0, 40,  0],
       ...,
       [40, 10,  4, ...,  0, 40,  0],
       [39, 13,  4, ...,  0, 50,  1],
       [50,  9,  4, ...,  0, 40,  0]])

In [84]:
#pulling out of the data a specific column(age) with index 0
age = np.array(data[:,0])
print(age)


[39 50 38 53 28 37 49 52 31 42 37 30 23 32 40 34 25 32 38 43 40 54 35 43
 59 56 19 54 39 49 23 20 45 30 22 48 21 19 31 48 31 53 24 49 25 57 53 44
 41 29 25 18 47 50 47 43 46 35 41 30 30 32 48 42 29 36 28 53 49 25 19 31
 29 23 79 27 40 67 18 31 18 52 46 59 44 53 49 33 30 43 57 37 28 30 34 29
 48 37 48 32 76 44 47 20 29 32 17 30 31 42 24 38 56 28 36 53 56 49 55 22
 21 40 30 29 19 47 20 31 35 39 28 24 38 37 46 38 43 27 20 49 61 27 19 45
 70 31 22 36 64 43 47 34 33 21 52 48 23 71 29 42 68 25 44 28 45 36 39 46
 18 66 27 28 51 27 28 27 21 34 18 33 44 43 30 40 37 34 41 53 31 58 38 24
 41 47 41 23 36 40 35 24 26 19 51 42 37 18 36 35 58 17 44 37 35 60 54 37
 50 38 45 25 31 64 90 54 53 18 60 66 75 65 35 41 25 33 28 59 40 41 38 23
 40 41 24 20 38 56 58 32 40 45 41 42 59 19 58 42 20 32 45 50 36 45 17 59
 26 37 19 64 33 33 61 17 50 27 30 43 44 35 25 24 22 42 34 60 21 57 41 50
 25 50 36 31 29 21 27 65 37 39 24 38 48 21 31 55 24 43 26 46 35 41 26 34
 19 36 22 24 77 22 29 62 39 43 35 29 76 63 23 43 58

In [85]:
#using the max() function to find the maximum age
max_age = age.max()
print(max_age)

90


In [86]:
#using the min() function to find the minimum age
min_age = age.min()
print(min_age)

17


In [87]:
#using the mean() function to calculate the mean value of the age column
age_mean = age.mean()
print(age_mean)

38.051


In [88]:
#use the std() function to identify the standard deviation of the column age
age_std  = np.std(age)
print(age_std)

13.342803266180612


In [89]:
#pulling from the main data another column(race) with index of 2
race = np.array(data[:,2])
print(race)

[4 4 4 2 2 4 2 4 4 4 2 1 4 2 1 0 4 4 4 4 4 2 2 4 4 4 4 1 4 4 4 2 4 4 2 4 4
 4 4 4 4 4 4 4 4 2 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 1 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 2 4 4 4 4 2 4 2 4 4 4 4 4 4 4 4 4 2 4 4 4 4 1 4 4 4 4 4 2 4 4
 4 4 4 4 1 4 4 4 4 2 4 2 4 4 1 1 4 4 4 4 4 4 4 4 4 4 4 4 2 2 4 4 2 4 2 4 4
 2 4 4 4 4 2 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 2 4 0 1 4 2 4 4 4 4 4 4
 2 2 4 4 0 4 4 4 2 2 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 2 2 4 4 1 4 4 4
 4 4 4 4 4 4 1 4 4 4 4 4 4 4 4 4 2 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 2 4
 4 1 4 4 4 1 4 4 1 4 4 4 4 4 4 1 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 4 2 4 4
 4 4 4 4 4 2 2 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4 4
 4 4 4 2 2 4 4 4 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 4 2 4 4 4 4 4 4 4
 4 4 2 0 4 4 2 4 4 2 4 1 4 2 4 4 4 2 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 2 2 4 4 4 4 4 4 4 

In [90]:
# breaking the race column into subsets race_0,race_1,...,race_4
race_0=[]
race_1=[]
race_2=[]
race_3=[]
race_4=[]

for i in race:
  if i==0:
    race_0.append(i)
  if i==1:
    race_1.append(i)
  if i==2:
    race_2.append(i)
  if i==3:
    race_3.append(i)
  if i==4:
    race_4.append(i)

In [91]:
#finding the length of each each race subset above
l=[len(race_0),len(race_1),len(race_2),len(race_3),len(race_4),]
print(l)

[10, 27, 110, 6, 847]


In [92]:
#identifying the race with the minimum number of citizens
l=[len(race_0),len(race_1),len(race_2),len(race_3),len(race_4),]
minority_race =(min(l))
print(minority_race)

6


In [93]:
#Here we are defining senior citizen by pulling the age column and returning entries > 60years  
senior_citizen = np.array(data[:,0])
s_c = senior_citizen>60
senior = data[:][s_c]
print(senior)


[[   79    10     4     1     0     0    20     0]
 [   67     6     4     1     0     0     2     0]
 [   76    14     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     0]
 [   70    10     4     1     0     0    40     0]
 [   64     7     4     1     0  2179    40     0]
 [   71    10     2     1     0  1816     2     0]
 [   68     2     4     0     0     0    20     0]
 [   66    11     4     0     0     0    20     0]
 [   64     2     4     1     0     0    40     0]
 [   90     9     2     1     0  2206    40     0]
 [   66     9     4     1  1409     0    50     0]
 [   75    11     4     0     0     0    20     0]
 [   65     9     4     0     0     0    40     0]
 [   64     9     4     1     0     0    40     1]
 [   61     9     4     1     0     0    40     1]
 [   65     9     4     1     0     0    16     0]
 [   77    10     4     1     0     0    40     0]
 [   62     9     4     0     0     0    24     0]
 [   76    14     4     1     0

In [94]:
#pull the column working hours to find total working hours for seniors
working_hours = np.array(senior[:,6])
working_hours_sum = working_hours.sum()
print(working_hours_sum)

1917


In [95]:
#finding the length of senior citizen
print(len(senior))

61


In [96]:
#find the average working hours for senior citizens
avg_working_hours = working_hours_sum/len(senior)
print(avg_working_hours)

31.42622950819672


government policy is not followed


In [97]:
#from the main dataset pull column for education_number and filter it to identify highly education and lowly educated citizens 
education_num = np.array(data[:,1])

high_education = education_num>10
low_education = education_num<=10
high= np.array(data[high_education])
low= np.array(data[low_education])
print (high)
print(low)

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [28 13  2 ...  0 40  0]
 ...
 [45 14  4 ...  0 45  0]
 [48 13  4 ...  0 58  1]
 [39 13  4 ...  0 50  1]]
[[38  9  4 ...  0 40  0]
 [53  7  2 ...  0 40  0]
 [49  5  2 ...  0 16  0]
 ...
 [35  9  4 ...  0 45  0]
 [56  9  4 ...  0 55  1]
 [40 10  4 ...  0 40  0]]


In [98]:
#finding the average payform both highly educated and low educated citizens respectively
avg_pay_high = high.mean()
avg_pay_low = low.mean()
print(avg_pay_high)
print(avg_pay_low)

167.18119266055047
62.53844725111441
